### ISSUE TITLE
Can you provide more information about your project?

### ISSUE THREAD

**Issue by astrolemonade** [fernandochimi/scraping-github#1]
Hello !
I am interested in your project but I want more information about it before trying it, safety concerns. 
What does it scrap ? The full repository(with everything, releases, issues, attachments etc)
How does this application work ? Does it have an UI or is it terminal based ?

**Comment by fernandochimi** [comment]
Hello @cata0309 . How are you?
This project was made for an interview job process. In that time, I was developed to search over a page, get the page information and save in a text file. The commands was provided by terminal. 
Unfortunately I aborted this project because not make sense.
But if you want to get improve, make a fork :D

**Comment by astrolemonade** [comment]
Hello @fernandochimi and thank you for your quick reply ! I will think about it in the near future as I really want some projects safe and with the full info, just in case!
